services:
    frontend:
        build: ./frontend
        container_name: mp_frontend
        ports:
            - "80:80"
        depends_on:
            - backend
            - model
        networks:
            - mp_net

    backend:
        build: ./backend
        container_name: mp_backend
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            DB_HOST: mariadb
            DB_USER: mindman_user
            DB_PASS: 28925502
            DB_NAME: mindman
            JWT_SECRET: dev_jwt_secret
        depends_on:
            - mariadb
        networks:
            - mp_net

    model:
        build: ./model_predict
        container_name: mp_model
        ports:
            - "5001:5001"
        environment:
            MODEL_PREDICT_PORT: 5001
            MODEL_PATH: /app/model/rf_mcpr.pkl
            TRAINING_DATA_PATH: /app/data/NG項_最終維修建議對照.csv
            LOG_DIR: /app/logs
        volumes:
            - ./model_predict/data:/app/data
            - ./model_predict/model:/app/model
            - ./model_predict/logs:/app/logs
        networks:
            - mp_net

    train_model:
        build: ./train_model
        container_name: mp_train_model
        ports:
            - "8501:8501"
        environment:
            MERGE_GUI_PORT: 8501
            TRAIN_OUTPUT_DIR: /app/outputs
            MODEL_PREDICT_DATA_DIR: /shared/model_predict/data
            MODEL_PREDICT_MODEL_DIR: /shared/model_predict/model
        volumes:
            - ./train_model/outputs:/app/outputs
            - ./model_predict/data:/shared/model_predict/data
            - ./model_predict/model:/shared/model_predict/model
        networks:
            - mp_net

    mariadb:
        image: mariadb:latest
        container_name: mp_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 28925502
            MYSQL_DATABASE: mindman
            MYSQL_USER: mindman_user
            MYSQL_PASSWORD: 28925502
        ports:
            - "3306:3306"
        volumes:
            - ./mindman.sql:/docker-entrypoint-initdb.d/mindman.sql
        networks:
            - mp_net


networks:
    mp_net:
        driver: bridge
